---
services:
  wiremock:
    container_name: "Wiremock"
    environment:
      TZ: "Pacific/Auckland"
      WIREMOCK_OPTIONS: "--verbose"
    image: "wiremock/wiremock:latest"
    ports:
    - "25710:8080"
    volumes:
    - "./wiremock:/home/wiremock"
