---
services:
  gallagher:
    container_name: "Gallagher"
    depends_on:
    - "nginx"
    env_file:
    - ".env"
    environment:
      TZ: "Pacific/Auckland"
    expose:
    - "8080"
    image: "ghcr.io/buried-in-code/gallagher:latest"
    networks:
    - "gallagher-network"
    restart: "unless-stopped"
  nginx:
    container_name: "Nginx"
    environment:
      TZ: "Pacific/Auckland"
    image: "nginx:latest"
    networks:
    - "gallagher-network"
    ports:
    - "80:80"
    restart: "unless-stopped"
    volumes:
    - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
networks:
  gallagher-network:
    driver: "bridge"
