services:
  gallagher:
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    container_name: 'Gallagher'
    environment:
      TZ: 'Pacific/Auckland'
      SPRING_PROFILES_ACTIVE: 'local'
    expose:
      - '8080'
    networks:
      - 'gallagher-network'
    restart: 'unless-stopped'

  nginx:
    container_name: 'Nginx'
    environment:
      TZ: 'Pacific/Auckland'
    image: 'nginx:latest'
    networks:
      - 'gallagher-network'
    ports:
      - '80:80'
    restart: 'unless-stopped'
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.cong:ro'

networks:
  gallagher-network:
    driver: bridge
