---
gallagher:
  api-key: "${GALLAGHER_API_KEY}"
  base-url: "${GALLAGHER_BASE_URL}"
  cert-path: "${GALLAGHER_CERT_PATH}"
  key-path: "${GALLAGHER_KEY_PATH}"
logging:
  level:
    root: "INFO"
    org.springframework.web.filter.CommonsRequestLoggingFilter: "DEBUG"
  pattern:
    console: "[%highlight(%d{yyyy-MM-dd HH:mm:ss})] [%highlight(%-5level)] [%highlight(%logger{2})]\
      \ %msg%n"
