---
gallagher:
  api-key: "${GALLAGHER__API_KEY}"
  base-url: "${GALLAGHER__BASE_URL}"
  cert-path: "${GALLAGHER__CERT_PATH}"
  key-path: "${GALLAGHER__KEY_PATH}"
logging:
  level:
    root: "INFO"
    org.springframework.web.filter.CommonsRequestLoggingFilter: "DEBUG"
  pattern:
    console: "[%highlight(%d{yyyy-MM-dd HH:mm:ss})] [%highlight(%-5level)] [%highlight(%logger{2})]\
      \ %msg%n"
create:
  user:
    email: "${CREATE__USER__EMAIL}"
    firstName: "${CREATE__USER__FIRST_NAME}"
    lastName: "${CREATE__USER__LAST_NAME}"
    divisionHref: "${CREATE__USER__DIVISION_HREF}"
    accessGroupHref: "${CREATE__USER__ACCESS_GROUP_HREF}"
    externalId: "${CREATE__USER__EXTERNAL_ID}"
read:
  user:
    email: "${READ__USER__EMAIL}"
update:
  card:
    type-href: "${UPDATE__CARD__TYPE_HREF}"
    number: "${UPDATE__CARD__NUMBER}"
  user:
    email: "${UPDATE__USER__EMAIL}"
delete:
  email: "${DELETE__USER__EMAIL}"
