name: Deployment
on:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy to GHCR
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup qemu
        uses: docker/setup-qemu-action@v3.6.0
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3.10.0
      - name: Login to GHCR
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        uses: docker/metadata-action@v5.7.0
        id: meta
        with:
          images: |
            name=ghcr.io/buried-in-code/gallagher
          flavor: |
            latest=true
          tags: |
            type=pep440,pattern={{version}}
      - name: Build and Push
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          push: startsWith(github.ref, 'refs/tags/')
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
