---
name: "Integration"
"on":
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"
jobs:
  spotless-checks:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4"
    - uses: "actions/setup-java@v4"
      with:
        distribution: "temurin"
        java-version: 21
    - uses: "actions/cache@v4"
      with:
        path: "~/.gradle/caches\n~/.gradle/wrapper\n"
        key: "${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties')\
          \ }}"
        restore-keys: "${{ runner.os }}-gradle-\n"
    - name: "Run spotless"
      run: "./gradlew spotlessCheck"
  gradle-tests:
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v4"
    - uses: "actions/setup-java@v4"
      with:
        distribution: "temurin"
        java-version: 21
    - uses: "actions/cache@v4"
      with:
        path: "~/.gradle/caches\n~/.gradle/wrapper\n"
        key: "${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties')\
          \ }}"
        restore-keys: "${{ runner.os }}-gradle-\n"
    - name: "Run tests"
      run: "./gradlew test"
